package co.herod.adbwrapper

const val SHELL = "shell"
const val ADB = "adb"
const val DISABLE = "disable"
const val ENABLE = "enable"
const val SERVICE = "svc"
const val DEVICES = "devices"
const val KEY_SCREEN_STATE = "mScreenState"
const val INTENT_ACTION_VIEW = "android.intent.action.VIEW"
const val DEVICE_CONNECTED_DEVICE = "device"
const val DEVICE_EMULATOR = "emulator"
const val UI_DUMP_XML_PATH = "/sdcard/window_dump.xml"
const val DUMPSYS = "dumpsys"
const val INPUT = "input"